### ISSUE TITLE
Releasing Notion-Version 2021-08-16

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#104]
**Additional context**
Notion is releasing Notion-Version 2021-08-16 with the following backwards incompatible changes:

- Unknown Keys Will Fail Validation
- Rollup Property Types
- Append Block Children [#127]
- URL Safe Property IDs
- Empty Properties Are Now Returned

**Notion Api Changelog** : https://developers.notion.com/changelog/notion-version-2021-08-16#unknown-keys-will-fail-validation

**Comment by Scantheus** [comment]
For a quick experiment, I changed notion version in your client code, compiled, and attempted a simple create that works fine using v1.4.1 and got this exception. calling Client.Pages.CreateAsync(newPage)...

body failed validation. Fix one: body.parent.type should be not present, instead was `"database_id"`. body.parent.page_id should be defined, instead was `undefined`.

var newPage = NewPage(new DatabaseParent() { DatabaseId = myDbId, Type = ParentType.DatabaseId }); 

If I leave out Type = ParentType.DatabaseId (which isn't need in v1.4.1) I get this...
body failed validation. Fix one: body.parent.type should be not present, instead was `"Unknown"`. body.parent.page_id should be defined, instead was `undefined`..

**Comment by KoditkarVedant** [comment]
@Scantheus I got the point the that going forward we may not need to send the type property as it is unnecessary for the server but did not understood why you are getting `page_id` or `database_id` as `undefined` even when you provided the value.
