### ISSUE TITLE
Filters should not be serialized with default values, SinglePropertyFilter has wrong format

### ISSUE THREAD

**Issue by asevos** [notion-dotnet/notion-sdk-net#14]
I tripped over this bug trying to make a simple bot fetching tasks from my Notion. 
Here is the code I executed. I suspected I used filters wrong, but I couldn't find any other other way to do it. 
```C#
var client = new NotionClient(new ClientOptions
{
    AuthToken = "MY_TOKEN"
});

var dateFilter = new DateFilter
{
    Property = "When",
    OnOrAfter = DateTime.Now,
};
var queryParams = new DatabasesQueryParameters
{
    Filter = dateFilter,
};
var databaseId = "MY_DB_ID";

var results = await client.Databases.QueryAsync(databaseId, queryParams);
```
So the expected behavior was to get in `results` all my pages with property "When" being set to some date in the future. However, it fetched me all pages in my Notion database. 
I played around with it a bit to find out what is going on and found out that in `RestClinent.PostAsync()` serialized filter looked like this: 
```JSON
{"Filter":{"equals":"0001-01-01T00:00:00","before":"0001-01-01T00:00:00","after":"0001-01-01T00:00:00","on_or_before":"0001-01-01T00:00:00","on_or_after":"2021-05-28T18:29:03.0391769+03:00","is_empty":true,"is_not_empty":true,"Property":"When"}}
```
It added to filter all possible filter states, that were not `null`. This were all `bool`s and `DateTime` properties. 

I updated `DateFilter` so it would serialize only properties added to it manually: 
```C#
public class DateFilter : SinglePropertyFilter
{
    [JsonProperty("equals")]
    [JsonConverter(typeof(IsoDateTimeConverter))]
    public Nullable<DateTime> Equal { get; set; }

    [JsonProperty("before")]
    [JsonConverter(typeof(IsoDateTimeConverter))]
    public Nullable<DateTime> Before { get; set; }

    [JsonProperty("after")]
    [JsonConverter(typeof(IsoDateTimeConverter))]
    public Nullable<DateTime> After { get; set; }

    [JsonProperty("on_or_before")]
    [JsonConverter(typeof(IsoDateTimeConverter))]
    public Nullable<DateTime> OnOrBefore { get; set; }

    [JsonProperty("on_or_after")]
    [JsonConverter(typeof(IsoDateTimeConverter))]
    public Nullable<DateTime> OnOrAfter { get; set; }

    [JsonProperty("past_week")]
    public Dictionary<string, object> PastWeek { get; set; }

    [JsonProperty("past_month")]
    public Dictionary<string, object> PastMonth { get; set; }

    [JsonProperty("past_year")]
    public Dictionary<string, object> PastYear { get; set; }

    [JsonProperty("next_week")]
    public Dictionary<string, object> NextWeek { get; set; }

    [JsonProperty("next_month")]
    public Dictionary<string, object> NextMonth { get; set; }

    [JsonProperty("next_year")]
    public Dictionary<string, object> NextYear { get; set; }

    [JsonProperty("is_empty")]
    public Nullable<bool> IsEmpty { get; set; }

    [JsonProperty("is_not_empty")]
    public Nullable<bool> IsNotEmpty { get; set; }
}
```
Then it was serializing correctly, however I ran into another issue: filters have wrong format, not supported by Notion API (https://developers.notion.com/reference/post-database-query#post-database-query-filter). I received filter of the following format:
```JSON
{
    "Filter": {
        "Property": "When",
        "on_or_after": "2021-05-28T18:35:56.0871291+03:00",
    }
}
```
While correct single property filter format according to docs would be: 
```JSON
{
    "filter": {
        "property": "When",
        "date": {
            "on_or_after": "2021-05-28T18:35:56.0871291+03:00"
        }
    }
}
```
@KoditkarVedant I could fix this issues and add a user friendly filter constructor, if you would accept my contributions.

**Comment by KoditkarVedant** [comment]
@asevos Thank you for logging the bug. Sure go ahead create a PR. I just noticed this is problem with all the filters. I'm not sure about if we should create a constructor but marking the properties as Nullable would be fine.

**Comment by asevos** [comment]
@KoditkarVedant, created PR#19
