### ISSUE TITLE
Exception in Client.Database.RetrieveAsync when database has icon.

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#161]
This happened in v2.0.  Still, I'm excited about this new release too!

Notion.Client.Database Schema = (Notion.Client.Database)await Client.Databases.RetrieveAsync(Id);
Exception: Could not create an instance of type Notion.Client.IPageIcon. Type is an interface or abstract class and cannot be instantiated. Path 'icon.type', line 1, position 93.

If I remove icon in Notion for database, it works fine.

Debug Window also shows...
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in Newtonsoft.Json.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll
Exception thrown: 'Newtonsoft.Json.JsonSerializationException' in System.Private.CoreLib.dll

**Comment by KoditkarVedant** [comment]
Thank you @Scantheus for reporting the bug. This has been fixed as part of [2.0.1](https://github.com/notion-dotnet/notion-sdk-net/releases/tag/2.0.1) release

**Comment by Scantheus** [comment]
Confirmed. Thanks Vedant!
