### ISSUE TITLE
Expose the IRestClient in INotionClient

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#163]
Currently, if there is any issue with existing endpoint the users of the library has no alternative way to call the NotionClient API's then need to either create their own http client to work around the problem until it gets fixed in the SDK.

To make this easier for the users - we can expose the IRestClient in INotionClient that users can use to call the API's directly and send the custom types or existing types to parse the response. Also we should expose the methods which will return the Raw http response.

**Comment by dluk** [comment]
Hi, can I work on this?
