### ISSUE TITLE
Number in NumberPropertyValue needs to be Nullable.

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#164]
As per  2021-08-16 Notion API version, empty database properties are now returned as null.

https://developers.notion.com/changelog/notion-version-2021-08-16#empty-database-properties-are-now-returned-as-null

I got this exception when querying and a record hand an empty Number type field.
Exception : Error converting value {null} to type 'System.Double'. Path 'number', line 1, position 1237.

I did not check other property types that may now be nullable.

**Comment by kashifsoofi** [comment]
Can I take this one
