### ISSUE TITLE
Add support for Table of contents block type

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#180]
Notion has added support for adding and retrieving `Table of Contents` and `Divider` block types.

**Table of Contents blocks**
You can now can add Table of Contents blocks to pages and other blocks.

Below is an example response from Append block children containing a Table of Contents block uploaded to Notion.
```
{
    "object": "list",
    "results": [
        {
            "object": "block",
            "id": "block-id",
            "created_time": "2021-10-14T18:10:00.000Z",
            "last_edited_time": "2021-10-14T18:10:00.000Z",
            "has_children": false,
            "archived": false,
            "type": "table_of_contents",
            "table_of_contents": {}
        }
    ],
    "next_cursor": null,
    "has_more": false
}
```

Notion API change log: https://developers.notion.com/changelog/table-of-contents-and-divider-block-types-are-now-supported

**Comment by mhall002** [comment]
Hi there, I'm looking to make my first open source contribution - would I be able to work on this issue?

**Comment by KoditkarVedant** [comment]
@mhall002 yeah sure.
