### ISSUE TITLE
 Notion.Client.NotionApiException: Could not find database with ID: 4f68615b-2dd8-4d3d-af71-.....

### ISSUE THREAD

**Issue by chuongmep** [notion-dotnet/notion-sdk-net#221]
**Describe the bug**
I used the concept api to work, reading the page is normal, but with the database, I can't browse, am I missing something?

**Screenshots**
![ảnh](https://user-images.githubusercontent.com/31106432/148638687-9929a1c0-db15-4501-b626-e47a8b10c08a.png)
**Code Sample**
```cs
static void Main(string[] args)
        {
            WebNotion wevNotion = new WebNotion();
            //wevNotion.GetTest();
            wevNotion.GetDataBase();
            Console.ReadKey();
        }

public class WebNotion {

 public WebNotion()
        {
            Client = NotionClientFactory.Create(new ClientOptions()
            {
                AuthToken = Token,
            });
        }
public void GetDataBase()
        {
            try
            {
                Task<Database> databases = Client.Databases.RetrieveAsync("ba876fca0bb446b6a27f311928272e62");
                string resultUrl = databases.Result.Id;
                Console.WriteLine(resultUrl);
            }
            catch (Exception e)
            {
                Console.WriteLine(e.ToString());
                throw;
            }
        }
}
```

**Comment by heytaichi** [comment]
you need to click Share and select Invite  bot  into your page
![](https://cdn.sspai.com/2021/05/16/596564aa8f8af83f06604033ec542bd9.png)

**Comment by chuongmep** [comment]
Yes, i have

**Comment by KoditkarVedant** [comment]
I can't really say what must be wrong. One of the reason is mentioned by @heytaichi. If you done that already check if you can find it using Search API. It could be that you may be using invalid ID or ID of a different object type (may be page or something).

**Comment by chuongmep** [comment]
Hi @KoditkarVedant, I have read document, may be error from documents, https://developers.notion.com/docs/getting-started#share-a-database-with-your-integration,example database ID in document guide is "https://www.notion.so/myworkspace/a8aec43384f447ed84390e8e42c2e089?v=...
                                  |--------- Database ID --------|" but a8aec43384f447ed84390e8e42c2e089 before character ?v is database ID, it took me 3 days to figure this stupid thing out. After edit and input again, it's working perfect.
