### ISSUE TITLE
Add table support

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#226]
Notion has added support for simple tables in the API.

### Simple tables and simple table rows
Tables are parent blocks for table row children. They can only contain children of type table_row.

When creating a table block via the [Append block children](https://developers.notion.com/reference/patch-block-children) endpoint, the table must have at least 1 table_row whose cells array has the same length as the table_width.

To fetch content for a table, fetch the the table_row children via [Retrieve block children](https://developers.notion.com/reference/get-block-children). The table block itself only contains formatting data, no content.

**Table block example:**
```json
{
    "type": "table",
    "table": {
        "table_width": 3,
        "has_column_header": false,
        "has_row_header": false
    }
}
```

**Table row block example:**
```json
{
  "type": "table_row",
  "table_row": {
    "cells": [
      [
        {
          "type": "text",
          "text": {
            "content": "column 1 content",
            "link": null
          },
          "annotations": {
            "bold": false,
            "italic": false,
            "strikethrough": false,
            "underline": false,
            "code": false,
            "color": "default"
          },
          "plain_text": "column 1 content",
          "href": null
        }
      ],
      [
        {
          "type": "text",
          "text": {
            "content": "column 2 content",
            "link": null
          },
          "annotations": {
            "bold": false,
            "italic": false,
            "strikethrough": false,
            "underline": false,
            "code": false,
            "color": "default"
          },
          "plain_text": "column 2 content",
          "href": null
        }
      ],
      [
        {
          "type": "text",
          "text": {
            "content": "column 3 content",
            "link": null
          },
          "annotations": {
            "bold": false,
            "italic": false,
            "strikethrough": false,
            "underline": false,
            "code": false,
            "color": "default"
          },
          "plain_text": "column 3 content",
          "href": null
        }
      ]
    ]
  }
}
```

**Comment by HermanSchoenfeld** [comment]
I can pledge USD $200 (payable via cryptocurrency) for this feature.

**Comment by KoditkarVedant** [comment]
Appreciate @HermanSchoenfeld for putting a bounty on this feature. I was hoping someone would pick and work on this feature. Now days, I hardly get some time to look after this project because of work.
