### ISSUE TITLE
Class name "URLPropertyScheam" is misspelled

### ISSUE THREAD

**Issue by flyingcroissant** [notion-dotnet/notion-sdk-net#232]
**Describe the bug**
The name of the class `URLPropertyScheam` has two issues:
1) "Schema" is misspelled.
2) The capitalization of "URL" is inconsistent with other classes (eg. `UrlPropertyValue` or `UrlProperty`).

**Expected behavior**
The name of the class `URLPropertyScheam` is correctly spelled and is capitalized consistently with other classes.

**Comment by KoditkarVedant** [comment]
This has been released as part of [2.2.4](https://github.com/notion-dotnet/notion-sdk-net/releases/tag/2.2.4) release.
