### ISSUE TITLE
Unexpected token exception: Databases.RetrieveAsync

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#299]
When upgrading from 3.0 to 3.1, Databases.RetrieveAsync now gets exception:
Error reading string. Unexpected token: StartArray. Path 'description', line 1, position 582.

**Comment by Scantheus** [comment]
Per Notion API spec, 'description' is an array of RichText objects. not a string. 

https://developers.notion.com/reference/database

**Comment by KoditkarVedant** [comment]
I messed up on my part. I have created a fix just figuring out how to release.
