### ISSUE TITLE
Number property causes exception in RetrievePagePropertyItem

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#309]
I was trying to work ahead to support v4.0.0 and RetrievePagePropertyItem and noticed it was already in v3.1.0 but got this error when trying to retrieve a number property on a simple 5 property database. Title, Date, Select, and RichText type properties work fine.

Newtonsoft.Json.JsonSerializationException
Error converting value 6043 to type 'Notion.Client.Number'. Path 'number', line 1, position 71.
Source=Newtonsoft.Json
Inner Exception 1:
ArgumentException: Could not cast or convert from System.Int64 to Notion.Client.Number.

**Comment by KoditkarVedant** [comment]
@Scantheus you trying library and reporting these bugs. If you are open you can also open the pull request and I'm happy to accept it. I mostly try to work on weekends on this library. Any help would be appreciated.

**Comment by KoditkarVedant** [comment]
Available as part of pre-release 4.0.0-preview-2.8.29.2022

**Comment by Scantheus** [comment]
This is fixed in preview.

**Comment by Scantheus** [comment]
@KoditkarVedant Sorry, The API is outside of my level of expertise. I'm a desktop developer with very little web API experience. I'm good for testing and sometimes pointing you where I think the issue is but, otherwise, I'm not helpful as a code contributor.

**Comment by KoditkarVedant** [comment]
4.0.0 Released
