### ISSUE TITLE
RetrievePagePropertyItem does not return any data for RichText properties (v4 preview)

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#317]
Adding JsonProperty attribute to RichTextPropertyItem.cs fixed it for me.

    public class RichTextPropertyItem : SimplePropertyItem
    {
        public override string Type => "rich_text";

        [JsonProperty("rich_text")]
        public RichTextBase RichText { get; set; }
    }

**Comment by KoditkarVedant** [comment]
Fix is available as part of pre-release version - 4.0.0-preview-4.9.11.2022

**Comment by KoditkarVedant** [comment]
4.0.0 Released
