### ISSUE TITLE
Fix typos

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#340]
I have noticed there are few typos which needs to be fixed.
- [x] IColumnChildrenBlock.cs
- [x] HeadingThreeeBlock.cs
- [x] RelationUpdatePropertySchema.cs
- [x] RelationPropertySchema.cs
- [x] HeadingThreeeUpdateBlock.cs

**Comment by sotiriszogos** [comment]
Hello, could you please assign it to me?

**Comment by KoditkarVedant** [comment]
done - assigned to you.

**Comment by sotiriszogos** [comment]
@KoditkarVedant as far as I understand on "HeadingThreeeBlock" and "HeadingThreeeUpdateBlock" the word "threee" is written wrong. On the other 3 classes what is the issue?

**Comment by KoditkarVedant** [comment]
@sotiriszogos Children is misspelled, and other classes has some properties which are misspelled.

**Comment by gauravagrwal** [comment]
Hi @KoditkarVedant, is this one already fixed, if not can I work on this.

**Comment by KoditkarVedant** [comment]
@gauravagrwal this has been already fixed.
