### ISSUE TITLE
Body failed validation when trying to update two properties at once

### ISSUE THREAD

**Issue by Vadim-Borovikov** [notion-dotnet/notion-sdk-net#345]
**Describe the bug**
Pages.UpdatePropertiesAsync fails when non-empty Text property gets updated.

**To Reproduce**
1. Set up a database with Text property.
2. Creare a page with non-empty Text property.
3. Get this page from the database to update it.
4. Try to set edit this property.
6. Observe errors (see below).

**Expected behavior**
Properties get updated, no errors from API.

**Comment by Vadim-Borovikov** [comment]
I've made some progress.
`UrlPropertyValue` gets cleared if pass `null` instead of object:
`UrlPropertyValue? uriValue = null;`

Still struggling with `RichTextPropertyValue` though.
When passing `null`, API returns error `Invalid property value for: "MyTestField".`

When passing `new RichTextPropertyValue { RichText = new List<RichTextBase>() };`, API returns error
`body failed validation. Fix one:
body.properties.MyTestField.id should be defined, instead was 'undefined'.
body.properties.MyTestField.name should be defined, instead was 'undefined'.
body.properties.MyTestField.start should be defined, instead was 'undefined'.`

**Comment by Vadim-Borovikov** [comment]
It gets stranger.

Initially, I am able to successfully fill empty Text property with code:
```c#
        RichTextPropertyValue result = new()
        {
            RichText = new List<RichTextBase>()
        };
        Text text = new() { Content = content };
        RichTextText item = new() { Text = text };
        result.RichText.Add(item);
        return result;
```

But I can neither clear nor edit non-empty Text. Errors from clearing are above, and error from editing is the same as the last one there:
> body failed validation. Fix one:
> body.properties.MyTestField.id should be defined, instead was `undefined`.
> body.properties.MyTestField.name should be defined, instead was `undefined`.
> body.properties.MyTestField.start should be defined, instead was `undefined`.

**Comment by Vadim-Borovikov** [comment]
Okay, so my experiments show that it is  something with multiple properties at nose.

This works:
```c#
    public async Task TestAsync(string pageId)
    {
        await TestUpdate(pageId, null, "https://github.com");
        await TestUpdate(pageId, "text 1", null);
        await TestUpdate(pageId, null, "https://github.com");
        await TestUpdate(pageId, "text 2", null);
        await TestUpdate(pageId, null, "https://github.com");
    }

    private async Task TestUpdate(string pageId, string? text, string? url)
    {
        Dictionary<string, PropertyValue?> properties = new()
        {
            { "Text", CreateTextValue(text) },
        };
        await _client.Pages.UpdatePropertiesAsync(pageId, properties);

        properties = new Dictionary<string, PropertyValue?>
        {
            { "URL", url is null ? null : new UrlPropertyValue { Url = url } }
        };
        await _client.Pages.UpdatePropertiesAsync(pageId, properties);
    }
```

and this produces errors for some reason:
```C#
    public async Task TestAsync(string pageId)
    {
        await TestUpdate(pageId, null, "https://github.com");
        await TestUpdate(pageId, "text 1", null);
        await TestUpdate(pageId, null, "https://github.com");
        await TestUpdate(pageId, "text 2", null);
        await TestUpdate(pageId, null, "https://github.com");
    }

    private async Task TestUpdate(string pageId, string? text, string? url)
    {
        Dictionary<string, PropertyValue?> properties = new()
        {
            { "Text", CreateTextValue(text) },
            { "URL", url is null ? null : new UrlPropertyValue { Url = url } }
        };
        await _client.Pages.UpdatePropertiesAsync(pageId, properties);
    }
```

**Comment by KoditkarVedant** [comment]
@Vadim-Borovikov I tried to reproduce this but it seems the problem is with the Notion API. I verified this by directly using Postman. May be you could report this at https://github.com/makenotion/notion-sdk-js
