### ISSUE TITLE
Expose Retry-After value into the exception

### ISSUE THREAD

**Issue by Poltuu** [notion-dotnet/notion-sdk-net#362]
**Is your feature request related to a problem? Please describe.**
Notion exposes a Retry-After after when reaching the rate limit. But the library hides it, forcing the developer to guess as to when to retry.

**Describe the solution you'd like**
Ideally, the NotionApiException should expose the value, probably as a Timespan?. 

**Describe alternatives you've considered**
We could also consider adding a RateLimitNotionApiException : NotionApiException exception class for this use case.

**Additional context**
[The doc](https://developers.notion.com/reference/request-limits)

**Comment by KoditkarVedant** [comment]
Related #253

**Comment by KoditkarVedant** [comment]
This has been released as part of [4.2.0](https://github.com/notion-dotnet/notion-sdk-net/releases/tag/4.2.0)
