### ISSUE TITLE
Cannot deserialize the database with button properties

### ISSUE THREAD

**Issue by kosaku-hayashi** [notion-dotnet/notion-sdk-net#416]
Querying a database containing "button properties" that are new to Notion will fail with the following exception.
Need an appropriate property class that can accept button properties.

Newtonsoft.Json.JsonSerializationException: 'Error converting value "button" to type 'Notion.Client.PropertyValueType'. Path 'type', line 1, position 4445.'

**Comment by kosaku-hayashi** [comment]
I will address this issue.

**Comment by RStolzlechner** [comment]
Can anyone merge the related PR? I have the same problem....
