### ISSUE TITLE
Add support to Archive (delete) a page

### ISSUE THREAD

**Issue by KoditkarVedant** [notion-dotnet/notion-sdk-net#64]
Update page api provides ability to achieve or delete a page by setting the achieve property when updating the page.

Set the archived parameter to true to archive or delete a page. For a page that is already archived, you can un-archive or restore that page by making the same request and setting archived to false. 

**API reference:** https://developers.notion.com/reference/patch-page#archive-delete-a-page

**Comment by ih-hira** [comment]
Do you need this implementation into your existing endpoints or into a new endpoint? If it is an existing endpoint, which endpoint needs to be modified? Is it UpdatePropertiesAsync?

**Comment by KoditkarVedant** [comment]
You can add new endpoint named `UpdateAsync` in `IPagesClient`. I'm thinking of deprecating the `UpdatePropertiesAsync` endpoints in future. I would also like a explicit `DeleteAsync` to just delete a page.

**Comment by ih-hira** [comment]
Ok, So, I am sharing my idea of how we can do that from my understanding. 
1. First of all, we have to keep in mind that a user can un-archive or restore a page at any time, so we have to make it soft delete.
2. To make it soft delete, when a user makes a delete request like DeletePage(pageId, true) we just update the value of the archive property true or false
3. When a user wants to Retrieve a page at that time we only return a page whose archive property is true.

Is it make sense or not with your requirements, please give your valuable feedback

**Comment by KoditkarVedant** [comment]
I think we can just implement `UpdateAsync` endpoint for `IPagesClient` at the moment & add Deprecated attribute on `UpdatePropertiesAsync` endpoint.

This is not required but if need we can add `ArchiveAsync` and `UnArchiveAsync` but I'm not sure atm as Notion API is changing 
 and user can use `UpdateAsync` if they want to un-archive a page. but if it is not much of work for you then go ahead.

I did not understood your third page I don't think this would affect any other API.

**Comment by Scantheus** [comment]
I just came across this issue as well while adding delete.

Koditkar, I think your approach is correct. Outside of properties, only the IsArchived flag is modifiable on a page. 
Something like UpdateAsync( pageId, properties, archive ).
This is consistent with your nice generic interface pattern.
