### ISSUE TITLE
Page create test case missing Parent.

### ISSUE THREAD

**Issue by Scantheus** [notion-dotnet/notion-sdk-net#69]
CreateAsync(newPage) in PageClientTests.cs should be getting an exception for you since it is missing Parent.

I based add page in my application on your test code and got exception. Works fine after adding Parent.

Your toolkit is exceptional. Thank you for creating it.

**Comment by KoditkarVedant** [comment]
@Scantheus Thank you for reporting it. Would you like to contribute? I would love to accept the PR.
